#!/usr/bin/env bash
# insight-recorder.sh — Auto-extract insights from task results + record KPI outcomes
#
# Required variables (set by caller before sourcing):
#   BOT_HOME

# --- Task outcome instrumentation (KPI) ---
record_outcome() {
    local task_id="$1"
    local success="$2"      # "true" or "false"
    local duration_ms="$3"
    local cost="${4:-0}"

    local payload
    payload=$(python3 -c "
import json, sys
print(json.dumps({
    'taskId': sys.argv[1],
    'success': sys.argv[2] == 'true',
    'durationMs': int(sys.argv[3]),
    'cost': float(sys.argv[4]),
    'ts': '$(date -u +%Y-%m-%dT%H:%M:%SZ)'
}))
" "$task_id" "$success" "$duration_ms" "$cost" 2>/dev/null) || return 0

    /bin/bash "${BOT_HOME}/scripts/mq-cli.sh" send "cron:${task_id}" kpi \
        "$payload" normal >/dev/null 2>/dev/null || true
}

# --- Auto-insights: save learnings from task output to vault ---
#
# Tier 4 Confidence-level Gate:
#   confidence 2 = 명시적 키워드(결론/핵심/학습/...) 포함 → 기록
#   confidence 1 = 키워드 없음, head -2 fallback → 기록 SKIP (halluc 방지)
#   confidence 0 = 빈 출력 → 기록 SKIP
#
# 이전에는 confidence 1도 기록했는데, 이게 vault에 hallucination 누적의 주범이었음.
# 이제는 confidence=2만 기록하고, confidence=1은 카운터만 올려서 추세 관측.
record_insight() {
    local task_name="$1"
    local output="$2"

    # Exclude log-only tasks from insight recording
    case "$task_name" in
        system-health|rate-limit-check|disk-alert|rag-health|token-sync|memory-cleanup|security-scan|calendar|github-monitor|test-echo|code-auditor)
            return 0
            ;;
    esac

    local vault_dir="${VAULT_DIR:-$HOME/vault}/02-daily/insights"
    local insight_file
    insight_file="$vault_dir/$(date +%Y-%m-%d).md"
    local skipped_log="${BOT_HOME}/logs/insight-skipped.log"

    # Skip if vault doesn't exist
    if [[ ! -d "${VAULT_DIR:-$HOME/vault}" ]]; then
        return 0
    fi

    mkdir -p "$vault_dir"

    # --- Confidence level classification ---
    local confidence=0
    local insight_lines=""

    if [[ -z "$output" ]]; then
        confidence=0
    else
        insight_lines=$(echo "$output" | grep -iE '(결론|핵심|학습|발견|중요|인사이트|insight|summary|key takeaway|conclusion)' | head -3)
        if [[ -n "$insight_lines" ]]; then
            confidence=2
        else
            confidence=1
        fi
    fi

    # --- Confidence gate: 2 미만은 vault 기록 skip ---
    if (( confidence < 2 )); then
        # 관측용 로그만 남김 (vault는 오염 안 시킴)
        mkdir -p "$(dirname "$skipped_log")" 2>/dev/null || true
        printf '[%s] task=%s confidence=%d reason=%s\n' \
            "$(date +%Y-%m-%dT%H:%M:%S)" \
            "$task_name" \
            "$confidence" \
            "$(if (( confidence == 0 )); then echo empty_output; else echo no_insight_keywords; fi)" \
            >> "$skipped_log" 2>/dev/null || true
        return 0
    fi

    # Create file header with frontmatter if new
    if [[ ! -f "$insight_file" ]]; then
        local today
        today="$(date +%Y-%m-%d)"
        {
            echo "---"
            echo "title: \"Insights — ${today}\""
            echo "tags: [area/daily, type/insight]"
            echo "created: ${today}"
            echo "updated: ${today}"
            echo "---"
            echo ""
            echo "# Insights — ${today}"
            echo ""
            echo "> Auto-generated by ask-claude.sh (confidence >= 2)"
            echo ""
        } > "$insight_file"
    fi

    # Append insight with confidence marker
    {
        echo "## $(date +%H:%M) — $task_name (confidence: $confidence)"
        echo ""
        echo "$insight_lines"
        echo ""
    } >> "$insight_file"

    echo "[insight] Saved to $insight_file (confidence=$confidence)" >&2
}
