#!/usr/bin/env bash
# insight-recorder.sh — Auto-extract insights from task results + record KPI outcomes
#
# Required variables (set by caller before sourcing):
#   BOT_HOME

# --- Task outcome instrumentation (KPI) ---
record_outcome() {
    local task_id="$1"
    local success="$2"      # "true" or "false"
    local duration_ms="$3"
    local cost="${4:-0}"

    local payload
    payload=$(python3 -c "
import json, sys
print(json.dumps({
    'taskId': sys.argv[1],
    'success': sys.argv[2] == 'true',
    'durationMs': int(sys.argv[3]),
    'cost': float(sys.argv[4]),
    'ts': '$(date -u +%Y-%m-%dT%H:%M:%SZ)'
}))
" "$task_id" "$success" "$duration_ms" "$cost" 2>/dev/null) || return 0

    /bin/bash "${BOT_HOME}/scripts/mq-cli.sh" send "cron:${task_id}" kpi \
        "$payload" normal >/dev/null 2>/dev/null || true
}

# --- Auto-insights: save learnings from task output to vault ---
record_insight() {
    local task_name="$1"
    local output="$2"

    # Exclude log-only tasks from insight recording
    case "$task_name" in
        system-health|rate-limit-check|disk-alert|rag-health|token-sync|memory-cleanup|security-scan|calendar-alert|github-monitor|test-echo|code-auditor)
            return 0
            ;;
    esac

    local vault_dir="${VAULT_DIR:-$HOME/vault}/02-daily/insights"
    local insight_file
    insight_file="$vault_dir/$(date +%Y-%m-%d).md"

    # Skip if vault doesn't exist
    if [[ ! -d "${VAULT_DIR:-$HOME/vault}" ]]; then
        return 0
    fi

    mkdir -p "$vault_dir"

    # Extract insight keywords
    local insight_lines
    insight_lines=$(echo "$output" | grep -iE '(결론|핵심|학습|발견|중요|인사이트|insight|summary|key|takeaway)' | head -3)

    if [[ -z "$insight_lines" ]]; then
        insight_lines=$(echo "$output" | head -2)
    fi

    if [[ -z "$insight_lines" ]]; then
        return 0
    fi

    # Create file header with frontmatter if new
    if [[ ! -f "$insight_file" ]]; then
        local today
        today="$(date +%Y-%m-%d)"
        {
            echo "---"
            echo "title: \"Insights — ${today}\""
            echo "tags: [area/daily, type/insight]"
            echo "created: ${today}"
            echo "updated: ${today}"
            echo "---"
            echo ""
            echo "# Insights — ${today}"
            echo ""
            echo "> Auto-generated by ask-claude.sh"
            echo ""
        } > "$insight_file"
    fi

    # Append insight
    {
        echo "## $(date +%H:%M) — $task_name"
        echo ""
        echo "$insight_lines"
        echo ""
    } >> "$insight_file"

    echo "[insight] Saved to $insight_file" >&2
}
