#!/usr/bin/env node
/**
 * write-env.mjs — .env 파일 생성/업데이트
 *
 * Usage:
 *   node write-env.mjs \
 *     --discord-token TOKEN \
 *     --api-key KEY \
 *     --guild-id GUILD \
 *     --discord-owner ID \
 *     --owner-name NAME \
 *     [--merge]     ← 기존 .env 유지하며 제공된 키만 업데이트 (재설치용)
 *
 * --merge 플래그:
 *   - 기존 .env 파일이 있으면 내용을 보존하면서 제공된 키만 업데이트
 *   - 기존 파일이 없으면 신규 생성 (동일)
 *   - CHANNEL_IDS 등 사용자 커스텀 값 보존됨
 */
import { mkdirSync, writeFileSync, existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { homedir } from 'node:os';

const HOME = homedir();
const args = process.argv.slice(2);
const mergeMode = args.includes('--merge');

function getArg(flag) {
  const idx = args.indexOf(flag);
  return idx !== -1 ? args[idx + 1] : null;
}

const token     = getArg('--discord-token');
const apiKey    = getArg('--api-key');
const guildId   = getArg('--guild-id');
const ownerId   = getArg('--discord-owner');
const ownerName = getArg('--owner-name');

const botHome    = join(HOME, '.local', 'share', 'jarvis');
const jarvisHome = join(HOME, '.jarvis');

const primaryEnvPath = join(jarvisHome, '.env');
const syncEnvPath    = join(botHome, '.env');

const ALL_DIRS = [
  jarvisHome, join(jarvisHome, 'config'),
  botHome,
  join(botHome, 'logs'), join(botHome, 'state'), join(botHome, 'context'),
  join(botHome, 'inbox'), join(botHome, 'results'), join(botHome, 'rag'),
  join(botHome, 'data'), join(botHome, 'config'),
];

/**
 * 기존 .env 내용을 보존하며 updates 객체의 키만 교체.
 * 주석·빈 줄·포맷 유지. 기존에 없던 키는 끝에 추가.
 */
function mergeEnv(filePath, updates) {
  const raw = existsSync(filePath) ? readFileSync(filePath, 'utf-8') : '';
  // 파일이 없거나 비어있으면 빈 배열로 시작 (trailing newline 방지)
  const existing = raw.trimEnd();
  const updated = new Set();

  const lines = (existing ? existing.split('\n') : []).map(line => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) return line;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) return line;
    const key = trimmed.slice(0, eqIdx).trim();
    if (key in updates) {
      updated.add(key);
      return `${key}=${updates[key]}`;
    }
    return line;
  });

  for (const [k, v] of Object.entries(updates)) {
    if (!updated.has(k)) lines.push(`${k}=${v}`);
  }

  return lines.join('\n');
}

if (mergeMode) {
  // merge 모드: 제공된 인자만 업데이트
  const updates = {};
  if (token     !== null) updates['DISCORD_TOKEN']    = token;
  if (apiKey    !== null) updates['ANTHROPIC_API_KEY'] = apiKey;
  if (guildId   !== null) updates['GUILD_ID']          = guildId;
  if (ownerId   !== null) updates['OWNER_DISCORD_ID']  = ownerId;
  if (ownerName !== null) updates['OWNER_NAME']         = ownerName;

  if (Object.keys(updates).length === 0) {
    console.log(JSON.stringify({ status: 'skipped', reason: 'no updates provided' }));
    process.exit(0);
  }

  for (const dir of ALL_DIRS) mkdirSync(dir, { recursive: true });

  const mergedContent = mergeEnv(primaryEnvPath, updates);
  const paths = [primaryEnvPath, syncEnvPath];
  for (const p of paths) writeFileSync(p, mergedContent, { mode: 0o600 });

  console.log(JSON.stringify({ status: 'merged', updatedKeys: Object.keys(updates), paths }));

} else {
  // 신규 설치 모드: 전체 인자 필수
  const missing = [];
  if (!token)     missing.push('--discord-token');
  if (!apiKey)    missing.push('--api-key');
  if (!guildId)   missing.push('--guild-id');
  if (!ownerId)   missing.push('--discord-owner');
  if (!ownerName) missing.push('--owner-name');

  if (missing.length > 0) {
    console.error(JSON.stringify({ error: 'Missing required arguments', missing }));
    process.exit(1);
  }

  const content = `# Jarvis Infrastructure Environment
# Generated by onboarding skill — ${new Date().toISOString()}

DISCORD_TOKEN=${token}
ANTHROPIC_API_KEY=${apiKey}

# Discord server
GUILD_ID=${guildId}
OWNER_DISCORD_ID=${ownerId}
OWNER_NAME=${ownerName}

# Discord channels (onboarding 후 채널 추가 시 자동 업데이트)
CHANNEL_IDS=

# Data home
BOT_HOME=${botHome}
`;

  for (const dir of ALL_DIRS) mkdirSync(dir, { recursive: true });

  const paths = [primaryEnvPath, syncEnvPath];
  for (const p of paths) writeFileSync(p, content, { mode: 0o600 });

  console.log(JSON.stringify({ status: 'ok', paths }));
}
